apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: asset-testing-deployment
  name: asset-testing-lb
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: asset-testing-deployment
  type: LoadBalancer
status:
  loadBalancer: {}
