apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: asset-testing-deployment
  name: asset-testing-np
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: asset-testing-deployment
  type: NodePort
status:
  loadBalancer: {}
